# Generated by Django 5.2 on 2026-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselegal',
            name='tipo',
            field=models.CharField(choices=[('Base legal', 'Base Legal'), ('Biblioteca legal', 'Biblioteca Legal')], max_length=30),
        ),
    ]
