# Generated by Django 3.2.6 on 2025-12-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
