# Generated by Django 5.2 on 2026-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_baselegal_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselegal',
            name='tipo',
            field=models.CharField(choices=[('base legal', 'Base Legal'), ('biblioteca legal', 'Biblioteca Legal')], max_length=30),
        ),
    ]
