# Generated by Django 3.2.6 on 2025-12-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
