# Generated by Django 3.2.6 on 2025-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
