# Generated by Django 3.2.6 on 2025-12-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
