# Generated by Django 3.2.6 on 2025-12-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_perfil_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('PROXIMO', 'Próximo'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='PROXIMO', max_length=12),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
