# Generated by Django 3.2.6 on 2025-12-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20251218_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(default='PROXIMO', max_length=120),
        ),
    ]
