# Generated by Django 3.2.6 on 2025-12-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_noticia_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
