# Generated by Django 3.2.6 on 2025-12-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20251218_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_fin',
        ),
    ]
