# Generated by Django 3.2.6 on 2025-12-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_noticia_fecha_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha_inicio',
            new_name='fecha_publicacion',
        ),
    ]
