# Generated by Django 5.2 on 2025-12-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_fecha_inicio_noticia_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='portada',
        ),
    ]
