# Generated by Django 5.2 on 2025-12-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_perfil_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baselegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
