# Generated by Django 5.2 on 2025-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_baselegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselegal',
            name='tipo',
            field=models.CharField(default='Bases', max_length=30),
        ),
    ]
