# Generated by Django 5.2 on 2025-12-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_baselegal_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselegal',
            name='tipo',
            field=models.CharField(choices=[('BASE', 'Base Legal'), ('BIBLIOTECA', 'Biblioteca Legal')], default='BASE', max_length=30),
        ),
    ]
